const AMOUNT_ON_PAGE = 6;
const FIRST_COLUMN_SLICE = 0;
const SECOND_COLUMN_SLICE = 2;
const THIRD_COLUMN_SLICE = 4;
const ESC_KEY_CODE = 27;

export {
  AMOUNT_ON_PAGE,
  FIRST_COLUMN_SLICE,
  SECOND_COLUMN_SLICE,
  THIRD_COLUMN_SLICE,
  ESC_KEY_CODE,
};
