const AMOUNT_ON_PAGE = 6;
const FIRST_SLICE = 0;
const SECOND_SLICE = 2;
const THIRD_SLICE = 4;
const AMOUNT_IN_COLUMN = 2;

export { AMOUNT_ON_PAGE, FIRST_SLICE, SECOND_SLICE, THIRD_SLICE, AMOUNT_IN_COLUMN };
